---
driver:
  name: docker
  binary: /usr/bin/docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  puppet_yum_collections_repo: "https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm"
  puppet_apt_collections_repo: "http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb"

platforms:
  - name: centos-7.2
  - name: ubuntu-16.04

suites:
  - name: default
    manifest: site.pp
