---
driver:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules

platforms:
  - name: centos-7.2
  - name: ubuntu-14.04

suites:
  - name: default
    manifest: site.pp
